export const POST_CREATE_ACCOUNT_REQUEST = "POST_CREATE_ACCOUNT_REQUEST"
export const POST_CREATE_ACCOUNT_SUCCESSFULL = "POST_CREATE_ACCOUNT_SUCCESSFULL"
export const POST_CREATE_ACCOUNT_FAILURE = "POST_CREATE_ACCOUNT_FAILURE"


export const GET_LOGIN_ACCOUNT_REQUEST = "GET_LOGIN_ACCOUNT_REQUEST"
export const GET_LOGIN_ACCOUNT_SUCCESSFULL = "GET_LOGIN_ACCOUNT_SUCCESSFULL"
export const GET_LOGIN_ACCOUNT_FAILURE = "GET_LOGIN_ACCOUNT_FAILURE"

export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAILURE = "UPDATE_PASSWORD_FAILURE";

