export const GET_INFOSEC_DATA_REQUEST = "GET_INFOSEC_DATA_REQUEST"
export const GET_INFOSEC_DATA_SUCCESSFULL = "GET_INFOSEC_DATA_SUCCESSFULL"
export const GET_INFOSEC_DATA_FAILURE = "GET_INFOSEC_DATA_FAILURE"

export const PATCH_INFOSEC_DATA_REQUEST = "PATCH_INFOSEC_DATA_REQUEST";
export const PATCH_INFOSEC_DATA_SUCCESS = "PATCH_INFOSEC_DATA_SUCCESS";
export const PATCH_INFOSEC_DATA_FAILURE = "PATCH_INFOSEC_DATA_FAILURE";

export const POST_INFOSEC_DATA_REQUEST = "POST_INFOSEC_DATA_REQUEST";
export const POST_INFOSEC_DATA_SUCCESSFUL = "POST_INFOSEC_DATA_SUCCESSFUL";
export const POST_INFOSEC_DATA_FAILURE = "POST_INFOSEC_DATA_FAILURE";

